name: build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup zig
              uses: goto-bus-stop/setup-zig@v1
              with:
                  version: 0.9.0
            - name: Build
              run: zig build
          
            - name: Upload binary
              uses: actions/upload-artifact@v2
              with:
                  name: out
                  path: ./zig-out/

    release:
        needs: [build]
        runs-on: ubuntu-latest

        if: startsWith(github.ref, 'refs/tags')

        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with: 
                  path: ./artifacts

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ./artifacts/out/bin/bootx64.efi
